### ISSUE TITLE
Case-insensitive finding of "#+BEGIN_SRC"

### ISSUE THREAD

**Issue by langston-barrett** [OrgTangle/Worgle#1]
Emacs doesn't care if you write
```org
#+BEGIN_SRC
code
#+END_SRC
```
or
```org
#+begin_src
code
#+end_src
```
but Worgle is limited to the former.

**Comment by PaulBatchelor** [comment]
Good catch! In Worgle, the parsing is done with a simple string comparison, so it's only looking for the upper case one. The choice to go upper case was made for me by org-mode since the default macro for generating a source block uses upper case by default. Had that not been the case I probably would just stuck with lower case.

Something I just discovered now is that makers (tags?) are completely case insensitive, as this seems to be valid as well:

```
#+nAmE: foo
#+BeGiN_SrC bash :tangle ./file.sh
  echo foo
#+EnD_sRc
```

If I had to make a choice, though, I would probably choose the either/or route. Building a case-insensitive string matcher seems like more overhead/trouble than it is worth.

**Comment by langston-barrett** [comment]
Fair enough!
