### ISSUE TITLE
Skip whitespace at the beginning of lines

### ISSUE THREAD

**Issue by langston-barrett** [OrgTangle/Worgle#2]
Worgle can't find
```org
  #+BEGIN_SRC bash :tangle ./file.sh
  echo foo
  #+END_SRC
```
because it is indented and Worgle uses `strncmp` to match exactly on `#+BEGIN_SRC` as the first 11 characters of a line.

**Comment by PaulBatchelor** [comment]
It should also be noted that Worgle also wouldn't work on this because it also expects the `#+NAME` tag (marker? not sure what these are officially called) to immediately precede it. All these tags would need to be updated to check for white space. Maybe create some sort of `check_for_marker` abstraction that does the string matching with whitespace.

Out of curiosity, what is the benefit to indenting code blocks like this?

**Comment by langston-barrett** [comment]
In Spacemacs, `org-indent-mode` is on by default, so any `SRC` block under a heading will be indented.

**Comment by PaulBatchelor** [comment]
Hey @langston-barrett, this issue has been [moved to a new repo](https://github.com/PaulBatchelor/worgle/issues/2).
