### ISSUE TITLE
Don't require NAME for each code block

### ISSUE THREAD

**Issue by langston-barrett** [OrgTangle/Worgle#3]
I don't use noweb-style literate programming, so my code blocks are seldom `NAME`d. I'd prefer not to have to generate a bunch of names arbitrarily which will never be used.

**Comment by PaulBatchelor** [comment]
I'll certainly look into it. Coming from CWEB, I've never not used named code blocks, so I'd be curious to see how some of your org files look.

**Comment by langston-barrett** [comment]
Thanks for the quick response! I often do this with very small code files:
```org
Some prosaic description of the following script.
#+BEGIN_SRC python :tangle ./script.py
print("A very short Python script")
#+END_SRC

Some prosaic description of a few more files, other content, etc.
```

**Comment by PaulBatchelor** [comment]
In these situations, would the tangled file all be contained in that single block?

**Comment by langston-barrett** [comment]
Not necessarily, if there are multiple blocks with the same filename they get concatenated

**Comment by PaulBatchelor** [comment]
Ah gotcha. Trying to imagine how this would work out. It definitely would add some new complexity to this system, but I do agree that there are occasions where you don't want to use named blocks, especially when it's the top-level tangle block.

Named blocks are pretty core the underlying design of Worgle. Tangled files are via a top-block. Blocks are composed of segments. Blocks are all stored inside of a dictionary, and segments of code get appended to these blocks. Since everything up to this point has been named, everything gets put inside of the dictionary. The dictionary is used as a resource manager, and frees all the allocated blocks and segments. If an anonymous block/segment wouldn't be added to the dictionary, which would cause a memory leak because there isn't anything keeping track of it. So, I'd have to figure out a way to manage these separately. Some kind of global anonymous list perhaps?

The hand-coded parser/state machine would have to be updated. Right now, the Worgle parser expects `NAME` to precede `BEGIN_SRC`. It would have to explicitly handle cases where `BEGIN_SRC` happens without `NAME`.

I'd also have to change the behavior of the "tangle" option. Right now, it is assumed that tangle is called exactly once per file. When it encounters the tangle option, Worgle extracts the text and then appends it to the file list. It doesn't check to see if a file already exists. If the file does exist, Worgle would have to know to append to the existing block, not start a new file.

**Comment by PaulBatchelor** [comment]
Hey @langston-barrett, this issue has been [moved to a new repo](https://github.com/PaulBatchelor/worgle/issues/1).
